### PR TITLE
Chainlink 54 - Profile Panels and Popups Shall Respect Profile's Privacy Setting

### PR DESCRIPTION
**Pull request by Jeremyb498**
Made it so the profile modal and profile panel (in friend list) respect the user's privacy setting. This does make the profile's look very empty (especially on the profile panel) so we may want to fill that space somehow, I toyed with the idea of adding a message indicating the profile is private which helps, but is redundant with the lock icon. If we decide to fill that space that can be a future branch / issue.

[CHAINLINK-54](https://heartratehackers.atlassian.net/browse/CHAINLINK-54)

### CODE REVIEW

**Comment by Alec8888** [comment]
Made some changes. Private profile should show username not first last name. Created a var to use in multiple places.

**Comment by Jeremyb498** [comment]
Are we sure profile shouldn't show first and last name? I know the ticket says username, but I don't see the harm in giving at least the first name. That gives some information to modal, if we only show username and profile picture then the only new info the modal gives you for private users is the friend button.

**Comment by bakermo** [comment]
> Are we sure profile shouldn't show first and last name? I know the ticket says username, but I don't see the harm in giving at least the first name. That gives some information to modal, if we only show username and profile picture then the only new info the modal gives you for private users is the friend button.

We should just show username on private profiles unless Lincoln tells us otherwise. I think it makes sense for privacy. Some people might not want to share their names publicly so that people can't look them up and creep them on Facebook or whatever.

**Comment by bakermo** [comment]
@Jeremyb498 @Alec8888 notice an inconsistency here. On the ride card, when I view a private profile I am not friends with, I see the profile picture and username with a lock icon, as expected:

image

However, when I view the friend request, I see the user's name instead of username:

image

**Comment by bakermo** [comment]
also can we go ahead and set the feature flag to true, I think Lincoln will want this in prod right away

**Comment by Jeremyb498** [comment]
Made it so profile panel displayed the user name as requested. I also enabled private profiles in production via the feature flag (once this branch makes it to prod).

**Comment by Alec8888** [comment]
Looks goo to me, merging.

**Pull request merged**
