### PR TITLE
Chainlink 59 - Private Ride Filtering In Ride Feed

### PR DESCRIPTION
**Pull request by Jeremyb498**
Added private ride filtering to the ride feed page, including the ability to filter down by any combination of 'public', 'private' and 'invited'. There aren't many results for 'private' and 'invited' currently since there are only a handful of rides setup that way. The way I have it setup, in order for a private ride to be visible you have either be the host, RSVPed, or invited. Feature flags are only on the client, I didn't see anywhere where we had been feature flagging the server, but the reviewer is more then welcome to add one if they would like. If the privacy options are not supplied (aka the feature flag is turned off) then it should just return everything (the same way it would if none of the privacy filtering checkboxes are selected).

This also contains the ride feed tags for 'Private' and 'Invited' I know that was a separate issue, but it made more sense to me to combine them here since they both required similar modifications to the FETCH_RIDES query. Plus the tags help prove that the filtering is working as intended. Not to mention the entirety of the tags commit was like 15 lines of code (including CSS).

[CHAINLINK-59](https://heartratehackers.atlassian.net/browse/CHAINLINK-59)
[CHAINLINK-60](https://heartratehackers.atlassian.net/browse/CHAINLINK-60)

### CODE REVIEW

**Comment by Alec8888** [comment]
@Jeremyb498 
I merged in main. Tags look good. I think the filters need work:
1. I think if only the Public filter is checked, then private rides should not be in the ride feed. Even if current user is on the private ride.
2. Private filter only checked should not display public rides.
3. If only Invited is checked, ride feed should only display invited rides.

image
image

**Comment by Jeremyb498** [comment]
Hey Alec, filters work fine on my end, even in a completely new install.

When I select Public and then Search all the private rides are filtered out correctly. Can you check the Server side code and it's console to see if you are having an issue there? Maybe check the GraphQL response to make sure it is correctly updating every time you press Search.

As far as I can tell the only filter that may need to be adjusted is Invited, currently Invited rides show up when the Invited checkbox is off if every other condition for them to be visible is on. However I could see the argument that we want to explicitly hide Invited rides unless the Invited Checkbox is selected.

**Comment by Alec8888** [comment]
@Jeremyb498 Hey is this one ready for review?

**Comment by Jeremyb498** [comment]
Hey @Alec8888 I am still of the belief that this pull request has been ready to review from the beginning. When I demoed the code on Friday it was a fresh install of this branch and everything was working as intended there.

**Comment by bakermo** [comment]
@Jeremyb498 took me a bit, but was able to repro what Alec is seeing. It has something to do with the bike types all being set, like it is overriding the privacy filter:

image

Interestingly, if I don't choose any filters, I don't get any rides back. I was seeing this BEFORE this branch sometimes, but I think the problem is more complex now that we've added privacy filters, so I think its best to look at it here:

image

For whatever reason,  this particular user (mobaker91), I can't get it to show any rides unless I select at least one bike type filter.  For what its worth, I've changed the bike types on my profile to have all bike types and no bike types, back and forth, and I get this issue. I don't seem to get the issue on my main user (bakermo91)

**Comment by Jeremyb498** [comment]
I really don't know anymore. I'm pretty sure I was able to replicate it once (in the middle of testing different code for the filtering), but I can't replicate it again. I think what is most likely happening is somehow the graphql instance is returning an error and causing the page to maintain the existing list of rides, but again I have not been able to confirm that. 

Having all bikes selected works for me with both my profile and @bakermo's test profile.
image

@bakermo the reason your secondary profile doesn't get any events when no bike types are selected is because you have an empty "" bike type defined on the profile which is being silently passed to the backend:

image

If you guys are able to replicate it again, can you send me the graphql query and response? Like I said if it is failing, I think the most likely reason is because it is having an error in the match query itself.

**Comment by Jeremyb498** [comment]
Okay that was actually a really interesting bug.

@bakermo it turns out that your secondary profile had an empty "" bike type that was being implicitly supplied to the query, hence why that profile couldn't query anything with no bike types selected. I went ahead and fixed that.

image

As for the phantom bug that we were struggling to reproduce it turns out it was related to having our filters joined up somewhat incorrectly. I can't find a reference to it in the documentation, but I wonder if we there is a limitation to the number of $and elements we can have in the root of the $match query. My profile was set to Non-Binary so it had an $or statement which appears to be fine, however @bakermo's secondary profile was set to a man, so it had an $and statement which caused it to return everything (somehow). I moved the gender filter to be a subsection of the privacy filter so that we only have the one root conditional element and now everything appears to be working as intended. Let me know if you guys find anything else.

**Pull request merged**
